#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define WHEELBOT_OLED_SDA_GPIO GPIO_NUM_41
#define WHEELBOT_OLED_SCL_GPIO GPIO_NUM_42
// User-facing 0x78 is the 8-bit write address; ESP-IDF uses 7-bit 0x3C.
#define WHEELBOT_OLED_I2C_ADDRESS_7BIT 0x3C
#define WHEELBOT_OLED_WIDTH 128
#define WHEELBOT_OLED_HEIGHT 64
#define WHEELBOT_UART_TX_GPIO GPIO_NUM_17
#define WHEELBOT_UART_RX_GPIO GPIO_NUM_18
#define WHEELBOT_KEY1_GPIO GPIO_NUM_9
#define WHEELBOT_KEY2_GPIO GPIO_NUM_10
#define WHEELBOT_KEY3_GPIO GPIO_NUM_11

#define AUDIO_INPUT_SAMPLE_RATE 16000
// INMP441 and MAX98357A share BCLK/WS, so the duplex I2S bus must use a
// sample rate supported by the microphone. AudioService resamples cloud
// playback to the codec rate as needed.
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_MIC_GPIO_BCLK GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_WS GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_16
#define AUDIO_AMP_SD_GPIO GPIO_NUM_8

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#endif  // _BOARD_CONFIG_H_
