#ifndef _WHEELBOT_S3_AUDIO_CONFIG_H_
#define _WHEELBOT_S3_AUDIO_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_4
#define AUDIO_I2S_GPIO_WS GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#endif  // _WHEELBOT_S3_AUDIO_CONFIG_H_
